DROP DATABASE IF EXISTS DB_DAP;

CREATE DATABASE DB_DAP;

USE DB_DAP;

CREATE TABLE TB_CLIENTE
(
	CLI_ID			    INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CLI_ASSOCIACAO		VARCHAR(100) NOT NULL,
    CLI_CPF			    VARCHAR(11) NOT NULL,
    CLI_ARQUIVO        VARCHAR(40) NOT NULL,
    CLI_MUNICIPIO	    VARCHAR(100) NOT NULL,
    CLI_TELEFONE        INT(15),
    CLI_DATA			DATE 
);

